Rework how lighthouse checks are performed in CI: use the result of the lighthouse call, not the JS post-processing

diff --git a/.github/workflows/lighthouse.yml b/.github/workflows/lighthouse.yml
--- a/.github/workflows/lighthouse.yml
+++ b/.github/workflows/lighthouse.yml
@@ -31,11 +31,11 @@ jobs:
         run: lhci autorun --config=./lighthouserc.json
 
       - name: Add audit scores to the job summary
-        if: always()
+        if: ${{ !cancelled() }}
         run: node scripts/lighthouse-summary.mjs
 
       - name: Upload Lighthouse reports
-        if: always()
+        if: ${{ !cancelled() }}
         uses: actions/upload-artifact@v4
         with:
           name: lighthouse-reports
@@ -43,3 +43,10 @@ jobs:
           if-no-files-found: warn
           retention-days: 14
           include-hidden-files: true
+
+      # Final step: Force the job to fail if anything failed earlier
+      - name: Check for Pre-Always Failures
+        if: failure()
+        run: |
+          echo "A step failed before processing the lighthouse results. Failing the job now."
+          exit 1
